// <auto-generated />
using System;
using KnOwl.ControlPlane.Storage.EntityFramework.Design.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnOwl.Migrations
{
    [DbContext(typeof(KnOwlDbContext))]
    [Migration("20260602200953_AddVersionedSchemaTypes")]
    partial class AddVersionedSchemaTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.CommandDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Topic");

                    b.ToTable("Commands", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.CommandVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommandDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CommandDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("CommandVersions", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.EventDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Topic");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.EventVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EventDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("EventVersions", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.SchemaTypeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SchemaTypeDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: string",
                            IsActive = true,
                            IsSystem = true,
                            Name = "string",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: number",
                            IsActive = true,
                            IsSystem = true,
                            Name = "number",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: integer",
                            IsActive = true,
                            IsSystem = true,
                            Name = "integer",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: boolean",
                            IsActive = true,
                            IsSystem = true,
                            Name = "boolean",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: object",
                            IsActive = true,
                            IsSystem = true,
                            Name = "object",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: array",
                            IsActive = true,
                            IsSystem = true,
                            Name = "array",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: null",
                            IsActive = true,
                            IsSystem = true,
                            Name = "null",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.SchemaTypeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JsonSchema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SchemaTypeDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("BaseType", "IsActive");

                    b.HasIndex("SchemaTypeDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("SchemaTypeVersions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            BaseType = "string",
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            JsonSchema = "{\"type\":\"string\"}",
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111112"),
                            BaseType = "number",
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            JsonSchema = "{\"type\":\"number\"}",
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111112"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111113"),
                            BaseType = "integer",
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            JsonSchema = "{\"type\":\"integer\"}",
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111113"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111114"),
                            BaseType = "boolean",
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            JsonSchema = "{\"type\":\"boolean\"}",
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111114"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111115"),
                            BaseType = "object",
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            JsonSchema = "{\"type\":\"object\"}",
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111115"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111116"),
                            BaseType = "array",
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            JsonSchema = "{\"type\":\"array\"}",
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111116"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111117"),
                            BaseType = "null",
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            JsonSchema = "{\"type\":\"null\"}",
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111117"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        });
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.CommandVersion", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Design.Core.CommandDefinition", "CommandDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("CommandDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommandDefinition");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.EventVersion", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Design.Core.EventDefinition", "EventDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("EventDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDefinition");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.SchemaTypeVersion", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Design.Core.SchemaTypeDefinition", "SchemaTypeDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("SchemaTypeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchemaTypeDefinition");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.CommandDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.EventDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.SchemaTypeDefinition", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
