using KnOwl.Contracts.Artifacts;
using KnOwl.Contracts.Distribution;
// <auto-generated />
using System;
using KnOwl.ControlPlane.Storage.EntityFramework.Design.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnOwl.Migrations
{
    [DbContext(typeof(KnOwlDbContext))]
    [Migration("20260911003507_AddContractReleaseAttempts")]
    partial class AddContractReleaseAttempts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.ContractArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PayloadSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactType", "VersionId")
                        .IsUnique();

                    b.HasIndex("ArtifactType", "Topic", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ContractArtifacts", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.ContractRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CanceledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeployedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InReviewAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Draft");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("ContractReleases", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.ContractReleaseAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ReleaseTargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseTargetId", "StartedAtUtc");

                    b.ToTable("ContractReleaseAttempts", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.ContractReleaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("ReleaseId", "ArtifactId")
                        .IsUnique();

                    b.ToTable("ContractReleaseItems", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.ContractReleaseTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AvailableAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReleaseItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RolloutGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RuntimeNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuntimeVersionApplied")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("ReleaseItemId");

                    b.HasIndex("RuntimeNodeId", "Status");

                    b.HasIndex("ReleaseId", "ReleaseItemId", "RuntimeNodeId")
                        .IsUnique();

                    b.ToTable("ContractReleaseTargets", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.RuntimeEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsEnabled");

                    b.ToTable("RuntimeEnvironments", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.RuntimeNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessTokenTtlSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(86400);

                    b.Property<string>("ApiKeyReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AuthenticationMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributionMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EndpointApiPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EndpointBaseUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InboundAllowedScopes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InboundClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("InboundCredentialCreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InboundCredentialRevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InboundCredentialRotatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InboundCredentialStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Missing");

                    b.Property<string>("InboundKeyId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InboundLastFailureReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("InboundLastTokenFailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InboundLastTokenIssuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InboundSecretHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OutboundClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("OutboundCredentialImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutboundCredentialStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Missing");

                    b.Property<string>("OutboundKeyId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("OutboundLastTokenReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutboundRequestedScopes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProtectedOutboundSecret")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecretReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TokenRefreshSkewSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(300);

                    b.Property<int>("TokenValidationCacheTtlSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(300);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("InboundClientId");

                    b.HasIndex("IsEnabled", "Status");

                    b.ToTable("RuntimeNodes", (string)null);
                });

            modelBuilder.Entity("KnOwl.Runtime.Core.RuntimeContractArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeployedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PayloadSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SourceArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("SourceReleaseId");

                    b.HasIndex("ArtifactType", "Topic", "VersionNumber")
                        .IsUnique();

                    b.ToTable("RuntimeContractArtifacts", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.CommandDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("Topic");

                    b.ToTable("Commands", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.CommandVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CommandDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeployedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeprecatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InReviewAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("CommandDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("CommandVersions", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.ContractFieldMetadataDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ContractFieldMetadataDefinitions", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.ContractFieldMetadataVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ContractFieldMetadataDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ContractFieldMetadataDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ContractFieldMetadataVersions", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.EventDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("Topic");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.EventVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeployedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeprecatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("InReviewAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("EventDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("EventVersions", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.SchemaTypeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SchemaTypeDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: string",
                            IsActive = true,
                            IsSystem = true,
                            Key = "string",
                            Name = "string",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: number",
                            IsActive = true,
                            IsSystem = true,
                            Key = "number",
                            Name = "number",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: integer",
                            IsActive = true,
                            IsSystem = true,
                            Key = "integer",
                            Name = "integer",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: boolean",
                            IsActive = true,
                            IsSystem = true,
                            Key = "boolean",
                            Name = "boolean",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: object",
                            IsActive = true,
                            IsSystem = true,
                            Key = "object",
                            Name = "object",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: array",
                            IsActive = true,
                            IsSystem = true,
                            Key = "array",
                            Name = "array",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System schema type: Date",
                            IsActive = true,
                            IsSystem = true,
                            Key = "Date",
                            Name = "Date",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System schema type: DateTime",
                            IsActive = true,
                            IsSystem = true,
                            Key = "DateTime",
                            Name = "DateTime",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System schema type: TimeSpan",
                            IsActive = true,
                            IsSystem = true,
                            Key = "TimeSpan",
                            Name = "TimeSpan",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.SchemaTypeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("SchemaTypeDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SchemaTypeDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("SchemaTypeVersions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"string\",\"name\":\"string\",\"description\":\"JSON Schema basic type: string\",\"version\":\"1.0.0\",\"baseType\":\"string\",\"comment\":\"\",\"schema\":{\"type\":\"string\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111112"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"number\",\"name\":\"number\",\"description\":\"JSON Schema basic type: number\",\"version\":\"1.0.0\",\"baseType\":\"number\",\"comment\":\"\",\"schema\":{\"type\":\"number\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111112"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111113"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"integer\",\"name\":\"integer\",\"description\":\"JSON Schema basic type: integer\",\"version\":\"1.0.0\",\"baseType\":\"integer\",\"comment\":\"\",\"schema\":{\"type\":\"integer\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111113"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111114"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"boolean\",\"name\":\"boolean\",\"description\":\"JSON Schema basic type: boolean\",\"version\":\"1.0.0\",\"baseType\":\"boolean\",\"comment\":\"\",\"schema\":{\"type\":\"boolean\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111114"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111115"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"object\",\"name\":\"object\",\"description\":\"JSON Schema basic type: object\",\"version\":\"1.0.0\",\"baseType\":\"object\",\"comment\":\"\",\"schema\":{\"type\":\"object\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111115"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111116"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"array\",\"name\":\"array\",\"description\":\"JSON Schema basic type: array\",\"version\":\"1.0.0\",\"baseType\":\"array\",\"comment\":\"\",\"schema\":{\"type\":\"array\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111116"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111118"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"Date\",\"name\":\"Date\",\"description\":\"System schema type: Date\",\"version\":\"1.0.0\",\"baseType\":\"string\",\"comment\":\"\",\"schema\":{\"type\":\"string\",\"pattern\":\"^\\\\d{4}-\\\\d{2}-\\\\d{2}$\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111118"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111119"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"DateTime\",\"name\":\"DateTime\",\"description\":\"System schema type: DateTime\",\"version\":\"1.0.0\",\"baseType\":\"string\",\"comment\":\"\",\"schema\":{\"type\":\"string\",\"pattern\":\"^\\\\d{4}-\\\\d{2}-\\\\d{2}T\\\\d{2}:\\\\d{2}:\\\\d{2}(?:\\\\.\\\\d{1,7})?(?:Z|[+-]\\\\d{2}:\\\\d{2})?$\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111119"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111120"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"TimeSpan\",\"name\":\"TimeSpan\",\"description\":\"System schema type: TimeSpan\",\"version\":\"1.0.0\",\"baseType\":\"string\",\"comment\":\"\",\"schema\":{\"type\":\"string\",\"pattern\":\"^(?:\\\\d+\\\\.)?\\\\d{2}:\\\\d{2}:\\\\d{2}(?:\\\\.\\\\d{1,7})?$\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111120"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        });
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.ContractReleaseAttempt", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Distribution.Core.ContractReleaseTarget", "ReleaseTarget")
                        .WithMany("Attempts")
                        .HasForeignKey("ReleaseTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseTarget");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.ContractReleaseItem", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Distribution.Core.ContractArtifact", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnOwl.ControlPlane.Distribution.Core.ContractRelease", "Release")
                        .WithMany("Items")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.ContractReleaseTarget", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Distribution.Core.ContractArtifact", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnOwl.ControlPlane.Distribution.Core.ContractRelease", "Release")
                        .WithMany("Targets")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnOwl.ControlPlane.Distribution.Core.ContractReleaseItem", "ReleaseItem")
                        .WithMany("Targets")
                        .HasForeignKey("ReleaseItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KnOwl.ControlPlane.Distribution.Core.RuntimeNode", "RuntimeNode")
                        .WithMany("Targets")
                        .HasForeignKey("RuntimeNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Release");

                    b.Navigation("ReleaseItem");

                    b.Navigation("RuntimeNode");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.RuntimeNode", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Distribution.Core.RuntimeEnvironment", "Environment")
                        .WithMany("RuntimeNodes")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.CommandVersion", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Design.Core.CommandDefinition", "CommandDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("CommandDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommandDefinition");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.ContractFieldMetadataVersion", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Design.Core.ContractFieldMetadataDefinition", "ContractFieldMetadataDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("ContractFieldMetadataDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractFieldMetadataDefinition");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.EventVersion", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Design.Core.EventDefinition", "EventDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("EventDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDefinition");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.SchemaTypeVersion", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Design.Core.SchemaTypeDefinition", "SchemaTypeDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("SchemaTypeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchemaTypeDefinition");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.ContractRelease", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.ContractReleaseItem", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.ContractReleaseTarget", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.RuntimeEnvironment", b =>
                {
                    b.Navigation("RuntimeNodes");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.RuntimeNode", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.CommandDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.ContractFieldMetadataDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.EventDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.SchemaTypeDefinition", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}

