using KnOwl.Contracts.Artifacts;
// <auto-generated />
using System;
using KnOwl.ControlPlane.Storage.EntityFramework.Design.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnOwl.Migrations
{
    [DbContext(typeof(KnOwlDbContext))]
    [Migration("20260725200621_AddContractArtifacts")]
    partial class AddContractArtifacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnOwl.ControlPlane.Distribution.Core.ContractArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PayloadSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactType", "VersionId")
                        .IsUnique();

                    b.HasIndex("ArtifactType", "Topic", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ContractArtifacts", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.CommandDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("Topic");

                    b.ToTable("Commands", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.CommandVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CommandDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeployedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeprecatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InReviewAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("CommandDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("CommandVersions", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.ContractFieldMetadataDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ContractFieldMetadataDefinitions", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.ContractFieldMetadataVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ContractFieldMetadataDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ContractFieldMetadataDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ContractFieldMetadataVersions", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.EventDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("Topic");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.EventVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeployedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeprecatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("InReviewAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("EventDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("EventVersions", (string)null);
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.SchemaTypeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SchemaTypeDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: string",
                            IsActive = true,
                            IsSystem = true,
                            Key = "string",
                            Name = "string",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: number",
                            IsActive = true,
                            IsSystem = true,
                            Key = "number",
                            Name = "number",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: integer",
                            IsActive = true,
                            IsSystem = true,
                            Key = "integer",
                            Name = "integer",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: boolean",
                            IsActive = true,
                            IsSystem = true,
                            Key = "boolean",
                            Name = "boolean",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: object",
                            IsActive = true,
                            IsSystem = true,
                            Key = "object",
                            Name = "object",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JSON Schema basic type: array",
                            IsActive = true,
                            IsSystem = true,
                            Key = "array",
                            Name = "array",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System schema type: Date",
                            IsActive = true,
                            IsSystem = true,
                            Key = "Date",
                            Name = "Date",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System schema type: DateTime",
                            IsActive = true,
                            IsSystem = true,
                            Key = "DateTime",
                            Name = "DateTime",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System schema type: TimeSpan",
                            IsActive = true,
                            IsSystem = true,
                            Key = "TimeSpan",
                            Name = "TimeSpan",
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.SchemaTypeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("SchemaTypeDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SchemaTypeDefinitionId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("SchemaTypeVersions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"string\",\"name\":\"string\",\"description\":\"JSON Schema basic type: string\",\"version\":\"1.0.0\",\"baseType\":\"string\",\"comment\":\"\",\"schema\":{\"type\":\"string\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111112"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"number\",\"name\":\"number\",\"description\":\"JSON Schema basic type: number\",\"version\":\"1.0.0\",\"baseType\":\"number\",\"comment\":\"\",\"schema\":{\"type\":\"number\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111112"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111113"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"integer\",\"name\":\"integer\",\"description\":\"JSON Schema basic type: integer\",\"version\":\"1.0.0\",\"baseType\":\"integer\",\"comment\":\"\",\"schema\":{\"type\":\"integer\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111113"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111114"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"boolean\",\"name\":\"boolean\",\"description\":\"JSON Schema basic type: boolean\",\"version\":\"1.0.0\",\"baseType\":\"boolean\",\"comment\":\"\",\"schema\":{\"type\":\"boolean\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111114"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111115"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"object\",\"name\":\"object\",\"description\":\"JSON Schema basic type: object\",\"version\":\"1.0.0\",\"baseType\":\"object\",\"comment\":\"\",\"schema\":{\"type\":\"object\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111115"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111116"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"array\",\"name\":\"array\",\"description\":\"JSON Schema basic type: array\",\"version\":\"1.0.0\",\"baseType\":\"array\",\"comment\":\"\",\"schema\":{\"type\":\"array\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111116"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111118"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"Date\",\"name\":\"Date\",\"description\":\"System schema type: Date\",\"version\":\"1.0.0\",\"baseType\":\"string\",\"comment\":\"\",\"schema\":{\"type\":\"string\",\"pattern\":\"^\\\\d{4}-\\\\d{2}-\\\\d{2}$\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111118"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111119"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"DateTime\",\"name\":\"DateTime\",\"description\":\"System schema type: DateTime\",\"version\":\"1.0.0\",\"baseType\":\"string\",\"comment\":\"\",\"schema\":{\"type\":\"string\",\"pattern\":\"^\\\\d{4}-\\\\d{2}-\\\\d{2}T\\\\d{2}:\\\\d{2}:\\\\d{2}(?:\\\\.\\\\d{1,7})?(?:Z|[+-]\\\\d{2}:\\\\d{2})?$\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111119"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        },
                        new
                        {
                            Id = new Guid("21111111-1111-1111-1111-111111111120"),
                            CreatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefinitionJson = "{\"key\":\"TimeSpan\",\"name\":\"TimeSpan\",\"description\":\"System schema type: TimeSpan\",\"version\":\"1.0.0\",\"baseType\":\"string\",\"comment\":\"\",\"schema\":{\"type\":\"string\",\"pattern\":\"^(?:\\\\d+\\\\.)?\\\\d{2}:\\\\d{2}:\\\\d{2}(?:\\\\.\\\\d{1,7})?$\"}}",
                            IsActive = true,
                            SchemaTypeDefinitionId = new Guid("11111111-1111-1111-1111-111111111120"),
                            UpdatedAtUtc = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = "1.0.0"
                        });
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.CommandVersion", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Design.Core.CommandDefinition", "CommandDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("CommandDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommandDefinition");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.ContractFieldMetadataVersion", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Design.Core.ContractFieldMetadataDefinition", "ContractFieldMetadataDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("ContractFieldMetadataDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractFieldMetadataDefinition");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.EventVersion", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Design.Core.EventDefinition", "EventDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("EventDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDefinition");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.SchemaTypeVersion", b =>
                {
                    b.HasOne("KnOwl.ControlPlane.Design.Core.SchemaTypeDefinition", "SchemaTypeDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("SchemaTypeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchemaTypeDefinition");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.CommandDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.ContractFieldMetadataDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.EventDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("KnOwl.ControlPlane.Design.Core.SchemaTypeDefinition", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
