{{- if and .Values.runtime.enabled .Values.runtime.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "knowl.runtimeFullname" . }}
  labels:
    {{- include "knowl.runtimeLabels" . | nindent 4 }}
  {{- with .Values.runtime.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.runtime.ingress.className }}
  ingressClassName: {{ .Values.runtime.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.runtime.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ include "knowl.runtimeFullname" $ }}
            port:
              number: {{ $.Values.runtime.ingress.port }}
      {{- end }}
  {{- end }}
  {{- with .Values.runtime.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
