{{- if .Values.runtime.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowl.runtimeFullname" . }}
  labels:
    {{- include "knowl.runtimeLabels" . | nindent 4 }}
  {{- if or .Values.runtime.service.internal.enabled .Values.runtime.service.annotations }}
  annotations:
    {{- if .Values.runtime.service.internal.enabled }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    {{- if .Values.runtime.service.internal.subnet }}
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: {{ .Values.runtime.service.internal.subnet | quote }}
    {{- end }}
    {{- end }}
    {{- with .Values.runtime.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.runtime.service.type }}
  {{- if eq .Values.runtime.service.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.runtime.service.externalTrafficPolicy }}
  {{- if .Values.runtime.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.runtime.service.loadBalancerIP | quote }}
  {{- end }}
  {{- end }}
  ports:
  - port: {{ .Values.runtime.service.port }}
    targetPort: {{ .Values.runtime.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "knowl.runtimeSelectorLabels" . | nindent 4 }}
{{- end }}
