{{- if or .Values.connectionStrings.knowlDb (and .Values.runtime.enabled .Values.runtime.connectionStrings.knowlRuntimeDb) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowl.secretName" . }}
  labels:
    {{- include "knowl.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.connectionStrings.knowlDb }}
  ConnectionStrings__KnOwlDb: {{ .Values.connectionStrings.knowlDb | quote }}
  {{- end }}
  {{- if and .Values.runtime.enabled .Values.runtime.connectionStrings.knowlRuntimeDb }}
  ConnectionStrings__KnOwlRuntimeDb: {{ .Values.runtime.connectionStrings.knowlRuntimeDb | quote }}
  {{- end }}
{{- end }}

