apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowl.fullname" . }}
  labels:
    {{- include "knowl.labels" . | nindent 4 }}
  {{- if or .Values.service.internal.enabled .Values.service.annotations }}
  annotations:
    {{- if .Values.service.internal.enabled }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    {{- if .Values.service.internal.subnet }}
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: {{ .Values.service.internal.subnet | quote }}
    {{- end }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  {{- end }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "knowl.selectorLabels" . | nindent 4 }}

