{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knowl.serviceAccountName" . }}
  labels:
    {{- include "knowl.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.azureClientId | quote }}
{{- end }}

