<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\KnOwl.Contracts\KnOwl.Contracts.csproj" />
    <ProjectReference Include="..\..\src\KnOwl.ControlPlane\KnOwl.ControlPlane.csproj" />
    <ProjectReference Include="..\..\src\KnOwl.ControlPlane.Api\KnOwl.ControlPlane.Api.csproj" />
    <ProjectReference Include="..\..\src\KnOwl.ControlPlane.Application\KnOwl.ControlPlane.Application.csproj" />
    <ProjectReference Include="..\..\src\KnOwl.ControlPlane.Bootstrap\KnOwl.ControlPlane.Bootstrap.csproj" />
    <ProjectReference Include="..\..\src\KnOwl.ControlPlane.Storage.EntityFramework\KnOwl.ControlPlane.Storage.EntityFramework.csproj" />
    <ProjectReference Include="..\..\src\KnOwl.ControlPlane.WebUI\KnOwl.ControlPlane.WebUI.csproj" />
    <ProjectReference Include="..\..\src\KnOwl.Runtime\KnOwl.Runtime.csproj" />
    <ProjectReference Include="..\..\src\KnOwl.Runtime.Api\KnOwl.Runtime.Api.csproj" />
    <ProjectReference Include="..\..\src\KnOwl.Runtime.Application\KnOwl.Runtime.Application.csproj" />
    <ProjectReference Include="..\..\src\KnOwl.Runtime.Bootstrap\KnOwl.Runtime.Bootstrap.csproj" />
    <ProjectReference Include="..\..\src\KnOwl.Runtime.Storage.EntityFramework\KnOwl.Runtime.Storage.EntityFramework.csproj" />
    <ProjectReference Include="..\..\src\KnOwl.Runtime.WebUI\KnOwl.Runtime.WebUI.csproj" />
    <ProjectReference Include="..\..\samples\KnOwl.ControlPlaneHost.Sample\KnOwl.ControlPlaneHost.Sample.csproj" />
    <ProjectReference Include="..\..\samples\KnOwl.RuntimeHost.Sample\KnOwl.RuntimeHost.Sample.csproj" />
  </ItemGroup>

</Project>
