using KnOwl.Contracts.Distribution;
using System.ComponentModel.DataAnnotations;
using KnOwl.Contracts.Security;

namespace KnOwl.ControlPlane.Distribution.Core;

/// <summary>
/// Represents a runtime host registered as a distribution target for contract artifacts.
/// </summary>
public sealed class RuntimeNode
{
    /// <summary>
    /// Runtime node identifier.
    /// </summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Human-readable runtime node name.
    /// </summary>
    [Required]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Stable runtime node code used by runtime hosts when pulling artifacts.
    /// </summary>
    [Required]
    [MaxLength(100)]
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// Runtime environment identifier.
    /// </summary>
    public Guid? EnvironmentId { get; set; }

    /// <summary>
    /// Environment label associated with this runtime node.
    /// </summary>
    [MaxLength(100)]
    public string EnvironmentName { get; set; } = string.Empty;

    /// <summary>
    /// Artifact distribution mode for this runtime node.
    /// </summary>
    public DistributionMode DistributionMode { get; set; } = DistributionMode.Pull;

    /// <summary>
    /// Runtime endpoint base URI used for push delivery.
    /// </summary>
    [MaxLength(500)]
    public string EndpointBaseUri { get; set; } = string.Empty;

    /// <summary>
    /// Runtime endpoint API path used for push delivery.
    /// </summary>
    [MaxLength(200)]
    public string EndpointApiPath { get; set; } = string.Empty;

    /// <summary>
    /// Authentication mode used when pushing artifacts to this runtime node.
    /// </summary>
    public RuntimeAuthenticationMode AuthenticationMode { get; set; } = RuntimeAuthenticationMode.None;

    /// <summary>
    /// Client identifier used for client credentials authentication.
    /// </summary>
    [MaxLength(200)]
    public string ClientId { get; set; } = string.Empty;

    /// <summary>
    /// Secret reference used to resolve client credential secrets at runtime.
    /// </summary>
    [MaxLength(500)]
    public string SecretReference { get; set; } = string.Empty;

    /// <summary>
    /// Secret reference used to resolve API keys at runtime.
    /// </summary>
    [MaxLength(500)]
    public string ApiKeyReference { get; set; } = string.Empty;

    /// <summary>
    /// Registration status for this runtime node.
    /// </summary>
    public RuntimeNodeStatus Status { get; set; } = RuntimeNodeStatus.Active;

    /// <summary>
    /// Indicates whether distribution can target this runtime node.
    /// </summary>
    public bool IsEnabled { get; set; } = true;

    /// <summary>
    /// Indicates whether this runtime node was removed from active configuration.
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// UTC timestamp when this runtime node was removed from active configuration.
    /// </summary>
    public DateTime? DeletedAtUtc { get; set; }

    /// <summary>
    /// Optional description for operators.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Token lifetime in seconds for Control Plane-issued tokens.
    /// </summary>
    public int AccessTokenTtlSeconds { get; set; } = 86_400;

    /// <summary>
    /// Number of seconds before expiration when outbound tokens should be refreshed.
    /// </summary>
    public int TokenRefreshSkewSeconds { get; set; } = 300;

    /// <summary>
    /// Number of seconds to cache positive bearer-token validations.
    /// </summary>
    public int TokenValidationCacheTtlSeconds { get; set; } = 300;

    /// <summary>
    /// Client id generated by Control Plane for Runtime pull calls into Control Plane.
    /// </summary>
    [MaxLength(200)]
    public string InboundClientId { get; set; } = string.Empty;

    /// <summary>
    /// Credential key id generated by Control Plane.
    /// </summary>
    [MaxLength(200)]
    public string InboundKeyId { get; set; } = string.Empty;

    /// <summary>
    /// Hashed client secret generated by Control Plane.
    /// </summary>
    [MaxLength(500)]
    public string InboundSecretHash { get; set; } = string.Empty;

    /// <summary>
    /// Space-separated scopes allowed for Runtime calls into Control Plane.
    /// </summary>
    [MaxLength(500)]
    public string InboundAllowedScopes { get; set; } = string.Empty;

    /// <summary>
    /// Lifecycle status for the Control Plane-generated inbound credential.
    /// </summary>
    public ConnectionCredentialStatus InboundCredentialStatus { get; set; } = ConnectionCredentialStatus.Missing;

    /// <summary>
    /// UTC timestamp when the inbound credential was created.
    /// </summary>
    public DateTime? InboundCredentialCreatedAtUtc { get; set; }

    /// <summary>
    /// UTC timestamp when the inbound credential was rotated.
    /// </summary>
    public DateTime? InboundCredentialRotatedAtUtc { get; set; }

    /// <summary>
    /// UTC timestamp when the inbound credential was revoked.
    /// </summary>
    public DateTime? InboundCredentialRevokedAtUtc { get; set; }

    /// <summary>
    /// UTC timestamp when the last inbound token was issued.
    /// </summary>
    public DateTime? InboundLastTokenIssuedAtUtc { get; set; }

    /// <summary>
    /// UTC timestamp when the last inbound token request failed.
    /// </summary>
    public DateTime? InboundLastTokenFailedAtUtc { get; set; }

    /// <summary>
    /// Last inbound token failure reason.
    /// </summary>
    [MaxLength(2000)]
    public string InboundLastFailureReason { get; set; } = string.Empty;

    /// <summary>
    /// Client id imported from Runtime for Control Plane push calls into Runtime.
    /// </summary>
    [MaxLength(200)]
    public string OutboundClientId { get; set; } = string.Empty;

    /// <summary>
    /// Runtime credential key id imported by Control Plane.
    /// </summary>
    [MaxLength(200)]
    public string OutboundKeyId { get; set; } = string.Empty;

    /// <summary>
    /// Protected Runtime secret imported by Control Plane.
    /// </summary>
    [MaxLength(2000)]
    public string ProtectedOutboundSecret { get; set; } = string.Empty;

    /// <summary>
    /// Space-separated scopes Control Plane requests when calling Runtime.
    /// </summary>
    [MaxLength(500)]
    public string OutboundRequestedScopes { get; set; } = string.Empty;

    /// <summary>
    /// Lifecycle status for the Runtime credential imported by Control Plane.
    /// </summary>
    public ConnectionCredentialStatus OutboundCredentialStatus { get; set; } = ConnectionCredentialStatus.Missing;

    /// <summary>
    /// UTC timestamp when the outbound credential was imported.
    /// </summary>
    public DateTime? OutboundCredentialImportedAtUtc { get; set; }

    /// <summary>
    /// UTC timestamp when the last outbound token was received by Control Plane.
    /// </summary>
    public DateTime? OutboundLastTokenReceivedAtUtc { get; set; }

    /// <summary>
    /// UTC timestamp when the node was registered.
    /// </summary>
    public DateTime RegisteredAtUtc { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// UTC timestamp when the node was last updated.
    /// </summary>
    public DateTime? LastUpdatedAtUtc { get; set; }

    /// <summary>
    /// Release targets assigned to this runtime node.
    /// </summary>
    public ICollection<ContractReleaseTarget> Targets { get; set; } = [];

    /// <summary>
    /// Runtime environment navigation.
    /// </summary>
    public RuntimeEnvironment? Environment { get; set; }
}

