<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <ProjectReference Include="..\KnOwl.Contracts\KnOwl.Contracts.csproj" />
    <ProjectReference Include="..\KnOwl.ControlPlane\KnOwl.ControlPlane.csproj" />
    <ProjectReference Include="..\KnOwl.ControlPlane.Application\KnOwl.ControlPlane.Application.csproj" />
    <ProjectReference Include="..\KnOwl.ControlPlane.Storage.EntityFramework\KnOwl.ControlPlane.Storage.EntityFramework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ButterMorph.Json.Schema" Version="1.0.2" />
    <PackageReference Include="ButterMorph.Web.Razor" Version="1.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

</Project>
