<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>knowl-mongo-dev-secrets</UserSecretsId>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.EntityFrameworkCore" Version="9.1.1" Condition="'$(TargetFramework)' == 'net9.0'" />
    <PackageReference Include="MongoDB.EntityFrameworkCore" Version="10.0.1" Condition="'$(TargetFramework)' == 'net10.0'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\KnOwl.ControlPlane.Bootstrap\KnOwl.ControlPlane.Bootstrap.csproj" />
  </ItemGroup>

</Project>
