using KnOwl.Contracts.Distribution;
using System.ComponentModel.DataAnnotations;
using KnOwl.Contracts.Security;

namespace KnOwl.Runtime.Distribution;

/// <summary>
/// Represents a Control Plane node trusted by an KnOwl Runtime host for artifact distribution.
/// </summary>
public sealed class RuntimeDesignNode
{
    /// <summary>
    /// Runtime-local identifier for this Control Plane connection.
    /// </summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Runtime-local key used to identify this Control Plane node.
    /// </summary>
    [Required]
    [MaxLength(100)]
    public string Key { get; set; } = string.Empty;

    /// <summary>
    /// Human-readable Control Plane name.
    /// </summary>
    [Required]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Control Plane endpoint base URI used by runtime pull flows.
    /// </summary>
    [MaxLength(500)]
    public string EndpointBaseUri { get; set; } = string.Empty;

    /// <summary>
    /// Runtime node identifier assigned by this Control Plane.
    /// </summary>
    [MaxLength(100)]
    public string RemoteRuntimeNodeId { get; set; } = string.Empty;

    /// <summary>
    /// Distribution mode selected for this connection.
    /// </summary>
    public DistributionMode DistributionMode { get; set; } = DistributionMode.Hybrid;

    /// <summary>
    /// Token lifetime in seconds for Runtime-issued tokens.
    /// </summary>
    public int AccessTokenTtlSeconds { get; set; } = 86_400;

    /// <summary>
    /// Number of seconds before expiration when outbound tokens should be refreshed.
    /// </summary>
    public int TokenRefreshSkewSeconds { get; set; } = 300;

    /// <summary>
    /// Number of seconds to cache positive bearer-token validations.
    /// </summary>
    public int TokenValidationCacheTtlSeconds { get; set; } = 300;

    /// <summary>
    /// Client id generated by Runtime for Control Plane push calls into Runtime.
    /// </summary>
    [MaxLength(200)]
    public string InboundClientId { get; set; } = string.Empty;

    /// <summary>
    /// Runtime-generated inbound credential key id.
    /// </summary>
    [MaxLength(200)]
    public string InboundKeyId { get; set; } = string.Empty;

    /// <summary>
    /// Runtime-generated inbound secret hash.
    /// </summary>
    [MaxLength(500)]
    public string InboundSecretHash { get; set; } = string.Empty;

    /// <summary>
    /// Space-separated scopes allowed for Control Plane calls into Runtime.
    /// </summary>
    [MaxLength(500)]
    public string InboundAllowedScopes { get; set; } = string.Empty;

    /// <summary>
    /// Lifecycle status for the Runtime-generated inbound credential.
    /// </summary>
    public ConnectionCredentialStatus InboundCredentialStatus { get; set; } = ConnectionCredentialStatus.Missing;

    /// <summary>
    /// UTC timestamp when the inbound credential was created.
    /// </summary>
    public DateTime? InboundCredentialCreatedAtUtc { get; set; }

    /// <summary>
    /// UTC timestamp when the inbound credential was rotated.
    /// </summary>
    public DateTime? InboundCredentialRotatedAtUtc { get; set; }

    /// <summary>
    /// UTC timestamp when the inbound credential was revoked.
    /// </summary>
    public DateTime? InboundCredentialRevokedAtUtc { get; set; }

    /// <summary>
    /// UTC timestamp when the last inbound token was issued.
    /// </summary>
    public DateTime? InboundLastTokenIssuedAtUtc { get; set; }

    /// <summary>
    /// UTC timestamp when the last inbound token request failed.
    /// </summary>
    public DateTime? InboundLastTokenFailedAtUtc { get; set; }

    /// <summary>
    /// Last inbound token failure reason.
    /// </summary>
    [MaxLength(2000)]
    public string InboundLastFailureReason { get; set; } = string.Empty;

    /// <summary>
    /// Client id imported from Control Plane for Runtime pull calls into Control Plane.
    /// </summary>
    [MaxLength(200)]
    public string OutboundClientId { get; set; } = string.Empty;

    /// <summary>
    /// Control Plane credential key id imported by Runtime.
    /// </summary>
    [MaxLength(200)]
    public string OutboundKeyId { get; set; } = string.Empty;

    /// <summary>
    /// Protected Control Plane secret imported by Runtime.
    /// </summary>
    [MaxLength(2000)]
    public string ProtectedOutboundSecret { get; set; } = string.Empty;

    /// <summary>
    /// Space-separated scopes Runtime requests when calling Control Plane.
    /// </summary>
    [MaxLength(500)]
    public string OutboundRequestedScopes { get; set; } = string.Empty;

    /// <summary>
    /// Lifecycle status for the Control Plane credential imported by Runtime.
    /// </summary>
    public ConnectionCredentialStatus OutboundCredentialStatus { get; set; } = ConnectionCredentialStatus.Missing;

    /// <summary>
    /// UTC timestamp when the outbound credential was imported.
    /// </summary>
    public DateTime? OutboundCredentialImportedAtUtc { get; set; }

    /// <summary>
    /// UTC timestamp when the last outbound token was received by Runtime.
    /// </summary>
    public DateTime? OutboundLastTokenReceivedAtUtc { get; set; }

    /// <summary>
    /// Optional operator description.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Runtime-side lifecycle status for this Control Plane connection.
    /// </summary>
    public RuntimeDesignNodeStatus Status { get; set; } = RuntimeDesignNodeStatus.Pending;

    /// <summary>
    /// Indicates whether this Control Plane connection can be used.
    /// </summary>
    public bool IsEnabled { get; set; }

    /// <summary>
    /// UTC timestamp when this connection was created.
    /// </summary>
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// UTC timestamp when this connection was last updated.
    /// </summary>
    public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow;
}
